tasks:
  - init: |
      gp open .oci/config
      gp open .oci/oci_api_key.pem
      gp open README.md
      curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install-oci-cli.sh
      chmod +777 install-oci-cli.sh
      ./install-oci-cli.sh --accept-all-defaults
      export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True
      # add this line to ~/.profile - to make oci a recognized shell command
      echo 'oci() { ~/bin/oci "$@"; }' >> ~/.profile
      # reload ~/.profile
      . ~/.profile
      source ~/.bashrc
      # now oci is recognized as a command
      ## install Terraform and OCI Provider
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update && sudo apt install terraform
      ## install OCI provider
      cd /workspace/gitpod-oracle-cloud-infrastructure/.oci/terraform/
      terraform init 
      cd /workspace/gitpod-oracle-cloud-infrastructure
      ## install Fn Client
      curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      ## install Fn server
      docker pull fnproject/fnserver:latest
      docker pull fnproject/node:latest      
      ## install Kubectl  -  based on https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl
      sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubectl
      sleep 10s &&       
      gp sync-done fn-server-installed
  - name: Install Okit
    init: |
      docker build --tag okit --no-cache --force-rm https://github.com/oracle/oci-designer-toolkit.git
      docker run -d --rm -p 80:80 --volume /workspace/gitpod-oracle-cloud-infrastructure/okit/user/templates:/okit/templates --volume /workspace/gitpod-oracle-cloud-infrastructure/.oci:/root/.oci --volume /workspace/gitpod-oracle-cloud-infrastructure/.ssh:/root/.ssh --name okit okit
  - name: Run Fn Server
    init: gp sync-await fn-server-installed
    command: |
      fn start &



vscode:
  extensions:
    - Oracle.oracledevtools
